/*
 * placeholder.h
 *
 *  Created on: 28.04.2022
 *      Author: franz
 */

#ifndef COMPONENTS_LIBRDKAFKA_INCLUDE_INCLUDE_PLACEHOLDER_H_
#define COMPONENTS_LIBRDKAFKA_INCLUDE_INCLUDE_PLACEHOLDER_H_



#endif /* COMPONENTS_LIBRDKAFKA_INCLUDE_INCLUDE_PLACEHOLDER_H_ */
